### PR TITLE
Create simple CI using github actions.

### PR DESCRIPTION
**Pull request by mikalstill**
Add some simple starting point CI which verifies that the code at least compiles.

### CODE REVIEW

**Comment by mikalstill** [comment]
Hey @malaterre, I'm unsure why the compile here is failing. How does what's documented in INSTALL compare with how Debian acutally compiles this code. I'm gonna be honest and say its been two decades since I really touched any of this and I am definitely rust on C builds.

**Comment by malaterre** [comment]
@mikalstill the issue is right here:

`gcc  -g -O2   -o pnginfo pnginfo.o  -lm `

it is missing the `-lpng`

**Comment by malaterre** [comment]
I think you are missing the `autoconf` step AFAIK

**Comment by malaterre** [comment]
for reference:

* https://buildd.debian.org/status/fetch.php?pkg=pngtools&arch=amd64&ver=0.5%7Egit20120106.409eb16-1&stamp=1638543648&raw=0

**Comment by mikalstill** [comment]
Hmmm. I am running `./configure`, and that has a `pnginfo_LDADD = -lpng` in Makefile.am. Oh... I wonder if I need to run automake as well? Its been a very very long time since I've compiled this stuff.

**Comment by mikalstill** [comment]
I think I want whatever:

```
dh build-arch
   dh_update_autotools_config -a
   dh_autoreconf -a
```

Is doing...

**Comment by mikalstill** [comment]
That filename warning is awesome too. I should fix that as well.

**Comment by mikalstill** [comment]
I am not entirely sure if its a good idea or not to run `aclocal` / `autoconf` / `automake` like this in a CI job, but at least the code compiles now... @malaterre any comments before I merge this?

**Comment by malaterre** [comment]
LGTM. Pay attention that I am mostly a cmake user...

**Comment by mikalstill** [comment]
LOL, at least it has 'c' in its name. I write python and golang these days.

**Pull request merged**
