### PR TITLE
man/*.sgml: Various fixes to SGML code

### PR DESCRIPTION
**Pull request by malaterre**

### CODE REVIEW

**Review by mikalstill — APPROVED** [review]
Thanks.

**Comment by mikalstill** [comment]
Oh, needs a rebase. I'll do it if you don't beat me to it but I wont have time tonight.

**Comment by malaterre** [comment]
> Oh, needs a rebase. I'll do it if you don't beat me to it but I wont have time tonight.

done :)

**Review by mikalstill — APPROVED** [review]
LGTM

**Pull request merged**
