### PR TITLE
man/*.sgml: Use section 1 for general commands

### PR DESCRIPTION
**Pull request by malaterre**
section 3 is for library functions

### CODE REVIEW

**Review by mikalstill — COMMENTED** [review]
Ugh, these are actually generated by makerelease, a shell script from the mists of time. I need to think more about this one before we can do this because I think I need to resurrect the generator (or just have hard coded man pages). Thoughts welcome there.

**Comment by malaterre** [comment]
I call `dockook2man` directly in my Debian rules. I believe most Linux distros have `dockook2man` anyway, so generating the manpage is actually not helpful.

**Comment by malaterre** [comment]
But you are right you'll need to remove the *.3 files otherwise this will confuse users.

**Review by mikalstill — APPROVED** [review]
Looks good. I am going to remove the doc comments from the C code and just let people edit the SGML files from now on.

**Pull request merged**
