### PR TITLE
Move man page generation into the makefiles & update configure.ac

### PR DESCRIPTION
**Pull request by dfandrich**
The makerelease script now uses that to generate the man pages.
autoreconf no longer complains about obsolete autoconf macros.

### CODE REVIEW

**Review by mikalstill — APPROVED** [review]
This looks good to me, although I largely feel like the man pages should be pulled out of the code these days and not use autodocbook.

**Comment by mikalstill** [comment]
```
configure.ac:2: error: possibly undefined macro: AC_CHECK_INCLUDES_DEFAULT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
Error: Process completed with exit code 1.
```

**Comment by dfandrich** [comment]
This macro is defined in /usr/share/autoconf/autoconf/headers.m4 in my box,
and is part of the stock autoconf installation. What version of autoconf does
this error show up in?

**Comment by mikalstill** [comment]
This is the configuration for the CI job: https://github.com/mikalstill/pngtools/blob/master/.github/workflows/c.yml

It appears to be running on Ubuntu 20.04.3 with whatever packages are installed by default by github. Are we possibly missing a package in the CI job?

**Comment by dfandrich** [comment]
It looks like that macro was added autoconf 2.70 but Ubuntu 20.04 has 2.69. I'll figure out how to work around that.

**Comment by dfandrich** [comment]
It turns out that pngtools didn't actually use the defines created by that macro, so I just removed it. Please take another look.

**Comment by mikalstill** [comment]
Thanks for digging into it. Running the CI now.

**Comment by dfandrich** [comment]
Looks like the CI builds now need docbook2man since the man pages are being
built now. I've updated the PR to include that.

**Comment by dfandrich** [comment]
The CI user was trying to install to /usr/local but it doesn't have permission.
I've updated the PR to install elsewhere.

**Review by mikalstill — APPROVED** [review]
Thanks.

**Pull request merged**
